-- Google Map 
--  Latitude Range: -85 to +85
--  Longitude Range: -180 to +180
create table items( 
    id              INT AUTO_INCREMENT PRIMARY KEY,
    ownerId         VARCHAR(255) NOT NULL,
	name            VARCHAR(255),
	description     TEXT,
    `condition`     VARCHAR(255),
    category        VARCHAR(255),
    imageURLs       TEXT,
    tags            TEXT,
    numberOfReview  INT DEFAULT 0,
    averageRating   DECIMAL DEFAULT 0.0,
    lat             DECIMAL,
    lng             DECIMAL,
    price           DECIMAL,
	isActive        TINYINT DEFAULT 1
);
-- 100 items of user1 to user10 (user1's items from 1-10; ... ; user10's items from 91-100) 
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (1, 'user1@shareandget.com', 'mauris eget massa tempor convallis nulla neque libero convallis', 'quisque ut erat curabitur gravida nisi at nibh in hac', 'Good', 'Others', 'https://picsum.photos/id/172/320/320', 'at turpis donec posuere metus vitae ipsum', 0, 0, 49.141703, -122.840572, 12, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (2, 'user1@shareandget.com', 'natoque penatibus', 'maecenas ut massa quis augue luctus tincidunt nulla mollis molestie', 'Good', 'Cars', 'https://picsum.photos/id/286/320/320', 'integer tincidunt', 0, 0, 49.17762, -122.876353, 21, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (3, 'user1@shareandget.com', 'convallis nulla', 'tristique est et tempus semper est quam pharetra magna ac consequat metus', 'Good', 'Electronics', 'https://picsum.photos/id/855/320/320', 'natoque penatibus et magnis dis parturient montes nascetur', 0, 0, 49.202142, -122.861146, 167, 0);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (4, 'user1@shareandget.com', 'aliquam convallis nunc proin at turpis', 'vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu', 'New', 'Others', 'https://picsum.photos/id/836/320/320', 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia', 0, 0, 49.243156, -122.886898, 36, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (5, 'user1@shareandget.com', 'blandit ultrices enim lorem', 'rutrum at lorem integer tincidunt ante vel ipsum praesent blandit', 'Used', 'Others', 'https://picsum.photos/id/819/320/320', 'porttitor pede justo eu massa donec dapibus', 0, 0, 49.238762, -122.921989, 71, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (6, 'user1@shareandget.com', 'consequat dui nec nisi', 'faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum', 'New', 'Home and Garden', 'https://picsum.photos/id/698/320/320', 'penatibus et magnis dis parturient montes', 0, 0, 49.178722, -122.936769, 122, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (7, 'user1@shareandget.com', 'odio condimentum id luctus nec molestie', 'sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel', 'Like new', 'Electronics', 'https://picsum.photos/id/660/320/320', 'ipsum primis in faucibus', 0, 0, 49.194059, -122.98548, 68, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (8, 'user1@shareandget.com', 'viverra dapibus nulla suscipit ligula', 'pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu', 'New', 'Electronics', 'https://picsum.photos/id/177/320/320', 'mi sit amet lobortis', 0, 0, 49.239163, -123.14941, 65, 0);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (9, 'user1@shareandget.com', 'vitae quam suspendisse potenti nullam porttitor lacus at turpis donec', 'consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices', 'Like new', 'Home and Garden', 'https://picsum.photos/id/692/320/320', 'mattis nibh ligula', 0, 0, 49.169007, -122.997695, 103, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (10, 'user1@shareandget.com', 'eget rutrum at lorem integer tincidunt ante vel', 'hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut', 'Like new', 'Others', 'https://picsum.photos/id/994/320/320', 'sodales sed tincidunt eu felis fusce posuere', 0, 0, 49.110441, -123.060815, 135, 0);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (11, 'user2@shareandget.com', 'integer ac leo pellentesque ultrices mattis odio donec vitae', 'justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet', 'New', 'Electronics', 'https://picsum.photos/id/291/320/320', 'nulla elit ac nulla sed vel enim sit', 0, 0, 49.092759, -122.95429, 164, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (12, 'user2@shareandget.com', 'est risus auctor sed', 'ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit', 'Used', 'Others', 'https://picsum.photos/id/412/320/320', 'a odio in hac habitasse platea dictumst', 0, 0, 49.149755, -122.792138, 59, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (13, 'user2@shareandget.com', 'ultrices posuere', 'ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus', 'New', 'Home and Garden', 'https://picsum.photos/id/575/320/320', 'vivamus tortor duis mattis egestas metus aenean fermentum', 0, 0, 49.23737, -122.805765, 161, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (14, 'user2@shareandget.com', 'at nulla suspendisse potenti cras in purus eu magna', 'felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa', 'Good', 'Cars', 'https://picsum.photos/id/8/320/320', 'elementum in hac habitasse', 0, 0, 49.124722, -123.124763, 144, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (15, 'user2@shareandget.com', 'non mi integer ac neque', 'primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec', 'Used', 'Cars', 'https://picsum.photos/id/347/320/320', 'sapien non mi integer ac', 0, 0, 49.232583, -122.852088, 20, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (16, 'user2@shareandget.com', 'elit ac nulla sed vel enim', 'auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum', 'Like new', 'Others', 'https://picsum.photos/id/883/320/320', 'nunc proin at turpis', 0, 0, 49.162702, -122.967388, 137, 0);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (17, 'user2@shareandget.com', 'placerat praesent blandit nam', 'duis bibendum felis sed interdum venenatis turpis enim blandit mi', 'Used', 'Home and Garden', 'https://picsum.photos/id/22/320/320', 'diam vitae quam suspendisse potenti nullam', 0, 0, 49.104503, -122.90847, 58, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (18, 'user2@shareandget.com', 'elit proin interdum mauris non ligula pellentesque', 'nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non', 'Like new', 'Home and Garden', 'https://picsum.photos/id/267/320/320', 'dui nec nisi volutpat eleifend', 0, 0, 49.11676, -123.090274, 65, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (19, 'user2@shareandget.com', 'donec ut', 'sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut', 'New', 'Others', 'https://picsum.photos/id/92/320/320', 'nulla nisl nunc nisl duis bibendum felis sed', 0, 0, 49.197608, -122.792431, 131, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (20, 'user2@shareandget.com', 'ut at dolor quis', 'tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo', 'Good', 'Home and Garden', 'https://picsum.photos/id/645/320/320', 'vestibulum ante ipsum primis in faucibus orci', 0, 0, 49.109232, -123.134128, 18, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (21, 'user3@shareandget.com', 'at turpis donec posuere metus', 'montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id', 'New', 'Electronics', 'https://picsum.photos/id/843/320/320', 'imperdiet et commodo vulputate justo', 0, 0, 49.147145, -122.791893, 154, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (22, 'user3@shareandget.com', 'vivamus metus arcu adipiscing molestie hendrerit at', 'in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in', 'New', 'Others', 'https://picsum.photos/id/689/320/320', 'donec vitae', 0, 0, 49.178673, -123.023672, 110, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (23, 'user3@shareandget.com', 'sit amet eleifend pede libero quis orci nullam', 'natoque penatibus et magnis dis parturient montes nascetur ridiculus mus', 'Like new', 'Home and Garden', 'https://picsum.photos/id/736/320/320', 'urna ut tellus nulla ut erat id', 0, 0, 49.233866, -123.108674, 14, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (24, 'user3@shareandget.com', 'eu tincidunt in leo maecenas pulvinar lobortis est phasellus', 'primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat', 'Good', 'Home and Garden', 'https://picsum.photos/id/131/320/320', 'odio donec vitae nisi nam ultrices libero non mattis pulvinar', 0, 0, 49.206463, -122.817843, 132, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (25, 'user3@shareandget.com', 'volutpat sapien arcu', 'augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl', 'Used', 'Cars', 'https://picsum.photos/id/990/320/320', 'magna', 0, 0, 49.173717, -122.840473, 199, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (26, 'user3@shareandget.com', 'nec condimentum neque sapien placerat ante', 'orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec', 'Like new', 'Electronics', 'https://picsum.photos/id/339/320/320', 'vestibulum velit id pretium', 0, 0, 49.187716, -122.85258, 186, 0);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (27, 'user3@shareandget.com', 'et ultrices posuere cubilia curae mauris', 'quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti', 'Used', 'Cars', 'https://picsum.photos/id/873/320/320', 'nibh in quis justo maecenas rhoncus', 0, 0, 49.090267, -122.799639, 180, 0);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (28, 'user3@shareandget.com', 'a ipsum integer a nibh in quis justo maecenas', 'aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio', 'New', 'Home and Garden', 'https://picsum.photos/id/585/320/320', 'pulvinar nulla pede ullamcorper augue a suscipit nulla elit', 0, 0, 49.229937, -122.870919, 42, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (29, 'user3@shareandget.com', 'nascetur ridiculus mus etiam vel augue vestibulum', 'non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar', 'New', 'Others', 'https://picsum.photos/id/518/320/320', 'in leo', 0, 0, 49.236831, -122.899586, 32, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (30, 'user3@shareandget.com', 'cubilia curae duis faucibus accumsan odio curabitur convallis duis', 'velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat', 'Used', 'Cars', 'https://picsum.photos/id/887/320/320', 'posuere cubilia curae', 0, 0, 49.185303, -123.095204, 59, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (31, 'user4@shareandget.com', 'risus semper porta volutpat', 'eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare', 'Like new', 'Electronics', 'https://picsum.photos/id/368/320/320', 'pretium iaculis diam erat fermentum justo', 0, 0, 49.109938, -123.134462, 162, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (32, 'user4@shareandget.com', 'elementum nullam varius nulla', 'rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede', 'Like new', 'Cars', 'https://picsum.photos/id/611/320/320', 'primis in faucibus orci luctus et ultrices posuere cubilia curae', 0, 0, 49.15285, -123.164063, 56, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (33, 'user4@shareandget.com', 'pretium iaculis', 'eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien', 'Used', 'Electronics', 'https://picsum.photos/id/934/320/320', 'nunc viverra dapibus nulla suscipit ligula in lacus curabitur', 0, 0, 49.243598, -122.842816, 136, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (34, 'user4@shareandget.com', 'vivamus tortor', 'tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est', 'Good', 'Electronics', 'https://picsum.photos/id/676/320/320', 'aliquam', 0, 0, 49.234657, -123.005494, 43, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (35, 'user4@shareandget.com', 'vel nisl', 'quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et', 'New', 'Cars', 'https://picsum.photos/id/337/320/320', 'in felis donec semper sapien a', 0, 0, 49.205945, -122.836029, 195, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (36, 'user4@shareandget.com', 'nullam sit', 'at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula', 'Used', 'Others', 'https://picsum.photos/id/244/320/320', 'donec diam neque vestibulum', 0, 0, 49.226974, -123.135063, 68, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (37, 'user4@shareandget.com', 'interdum mauris non ligula pellentesque ultrices phasellus', 'nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec', 'Used', 'Cars', 'https://picsum.photos/id/326/320/320', 'fringilla rhoncus mauris enim leo rhoncus sed vestibulum', 0, 0, 49.221853, -122.861784, 127, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (38, 'user4@shareandget.com', 'ut suscipit a feugiat et eros vestibulum ac', 'consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo', 'Good', 'Others', 'https://picsum.photos/id/487/320/320', 'consequat varius integer ac leo pellentesque', 0, 0, 49.233996, -122.974802, 183, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (39, 'user4@shareandget.com', 'at turpis donec posuere', 'nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper', 'Like new', 'Electronics', 'https://picsum.photos/id/465/320/320', 'nibh ligula nec sem duis aliquam convallis nunc proin', 0, 0, 49.204237, -122.885214, 68, 0);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (40, 'user4@shareandget.com', 'sit amet nunc viverra dapibus nulla suscipit', 'id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus', 'Used', 'Others', 'https://picsum.photos/id/26/320/320', 'eros suspendisse accumsan', 0, 0, 49.238072, -123.177066, 99, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (41, 'user5@shareandget.com', 'ipsum primis in faucibus orci luctus et ultrices posuere', 'interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae', 'Good', 'Others', 'https://picsum.photos/id/560/320/320', 'volutpat convallis morbi odio odio elementum eu interdum eu tincidunt', 0, 0, 49.24203, -123.016336, 59, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (42, 'user5@shareandget.com', 'sem praesent id massa id nisl venenatis lacinia', 'orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus', 'Used', 'Home and Garden', 'https://picsum.photos/id/343/320/320', 'sapien cursus vestibulum', 0, 0, 49.21658, -123.157886, 104, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (43, 'user5@shareandget.com', 'diam id ornare', 'velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo', 'Good', 'Home and Garden', 'https://picsum.photos/id/189/320/320', 'consequat metus sapien ut nunc vestibulum ante ipsum primis in', 0, 0, 49.198581, -123.074524, 72, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (44, 'user5@shareandget.com', 'enim in tempor turpis nec euismod scelerisque quam turpis adipiscing', 'nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti', 'New', 'Home and Garden', 'https://picsum.photos/id/794/320/320', 'enim blandit mi in porttitor pede justo eu massa', 0, 0, 49.183934, -123.115243, 166, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (45, 'user5@shareandget.com', 'quis lectus suspendisse', 'iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis', 'Used', 'Others', 'https://picsum.photos/id/189/320/320', 'vehicula condimentum curabitur in libero ut massa', 0, 0, 49.129017, -122.841355, 68, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (46, 'user5@shareandget.com', 'ante nulla justo aliquam quis turpis eget', 'in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate', 'Good', 'Home and Garden', 'https://picsum.photos/id/388/320/320', 'faucibus orci luctus et', 0, 0, 49.241513, -123.061563, 200, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (47, 'user5@shareandget.com', 'consequat in consequat ut nulla', 'cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam', 'Used', 'Others', 'https://picsum.photos/id/869/320/320', 'adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus', 0, 0, 49.114457, -122.941231, 75, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (48, 'user5@shareandget.com', 'nec sem duis aliquam convallis nunc proin at turpis a', 'dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat', 'Like new', 'Electronics', 'https://picsum.photos/id/339/320/320', 'odio odio elementum eu interdum eu tincidunt in leo', 0, 0, 49.178103, -123.052149, 82, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (49, 'user5@shareandget.com', 'leo maecenas pulvinar lobortis est phasellus sit amet', 'justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea', 'Good', 'Electronics', 'https://picsum.photos/id/496/320/320', 'nisl venenatis', 0, 0, 49.143179, -122.786116, 39, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (50, 'user5@shareandget.com', 'ut ultrices', 'nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula', 'Good', 'Cars', 'https://picsum.photos/id/42/320/320', 'maecenas leo odio condimentum', 0, 0, 49.200854, -123.050345, 53, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (51, 'user6@shareandget.com', 'luctus et ultrices', 'odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus', 'Like new', 'Home and Garden', 'https://picsum.photos/id/854/320/320', 'ligula in lacus', 0, 0, 49.237478, -122.911344, 42, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (52, 'user6@shareandget.com', 'ultrices libero non mattis pulvinar nulla', 'ligula suspendisse ornare consequat lectus in est risus auctor sed', 'Used', 'Electronics', 'https://picsum.photos/id/714/320/320', 'nulla integer pede justo lacinia', 0, 0, 49.103992, -123.052038, 173, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (53, 'user6@shareandget.com', 'nibh in quis justo maecenas', 'ornare consequat lectus in est risus auctor sed tristique in tempus sit', 'New', 'Others', 'https://picsum.photos/id/146/320/320', 'maecenas', 0, 0, 49.123429, -123.005342, 177, 0);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (54, 'user6@shareandget.com', 'aenean lectus pellentesque eget nunc donec', 'natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et', 'Good', 'Others', 'https://picsum.photos/id/683/320/320', 'interdum in ante vestibulum', 0, 0, 49.14321, -122.955549, 138, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (55, 'user6@shareandget.com', 'in faucibus orci luctus et ultrices posuere cubilia curae', 'molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat', 'Good', 'Home and Garden', 'https://picsum.photos/id/240/320/320', 'in faucibus orci luctus et', 0, 0, 49.155396, -122.980345, 54, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (56, 'user6@shareandget.com', 'enim blandit mi in porttitor', 'lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque', 'Like new', 'Cars', 'https://picsum.photos/id/517/320/320', 'ipsum primis in faucibus orci luctus', 0, 0, 49.187321, -122.922607, 87, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (57, 'user6@shareandget.com', 'rutrum at lorem integer tincidunt ante', 'blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi', 'Used', 'Home and Garden', 'https://picsum.photos/id/79/320/320', 'nunc purus phasellus in felis', 0, 0, 49.156827, -122.965111, 130, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (58, 'user6@shareandget.com', 'sit amet lobortis sapien sapien non mi', 'lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare', 'New', 'Electronics', 'https://picsum.photos/id/876/320/320', 'semper est quam pharetra magna ac', 0, 0, 49.19244, -122.850423, 172, 0);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (59, 'user6@shareandget.com', 'in faucibus orci luctus et ultrices posuere', 'felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut', 'Like new', 'Cars', 'https://picsum.photos/id/152/320/320', 'cursus id turpis integer aliquet massa id lobortis', 0, 0, 49.100999, -123.049776, 30, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (60, 'user6@shareandget.com', 'elit ac nulla sed vel enim sit amet', 'ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent', 'Like new', 'Home and Garden', 'https://picsum.photos/id/817/320/320', 'maecenas pulvinar lobortis est phasellus sit amet', 0, 0, 49.210696, -123.046215, 42, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (61, 'user7@shareandget.com', 'orci luctus et ultrices posuere cubilia curae donec pharetra', 'luctus ultricies eu nibh quisque id justo sit amet sapien', 'Used', 'Home and Garden', 'https://picsum.photos/id/81/320/320', 'et', 0, 0, 49.167566, -123.009689, 17, 0);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (62, 'user7@shareandget.com', 'et ultrices', 'pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus', 'Like new', 'Others', 'https://picsum.photos/id/929/320/320', 'tempus vel pede morbi porttitor', 0, 0, 49.15086, -122.995437, 130, 0);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (63, 'user7@shareandget.com', 'consectetuer adipiscing elit', 'dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est', 'New', 'Home and Garden', 'https://picsum.photos/id/123/320/320', 'ipsum dolor sit amet consectetuer adipiscing', 0, 0, 49.198986, -123.157284, 21, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (64, 'user7@shareandget.com', 'non pretium quis', 'quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at', 'Good', 'Home and Garden', 'https://picsum.photos/id/972/320/320', 'platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum', 0, 0, 49.124896, -123.087979, 136, 0);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (65, 'user7@shareandget.com', 'congue etiam justo etiam pretium iaculis', 'justo in hac habitasse platea dictumst etiam faucibus cursus urna ut', 'New', 'Home and Garden', 'https://picsum.photos/id/371/320/320', 'dictumst aliquam augue quam sollicitudin vitae consectetuer', 0, 0, 49.206736, -123.036012, 17, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (66, 'user7@shareandget.com', 'ligula pellentesque ultrices phasellus id sapien in', 'eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse', 'New', 'Cars', 'https://picsum.photos/id/316/320/320', 'pretium', 0, 0, 49.240597, -122.808504, 99, 0);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (67, 'user7@shareandget.com', 'non interdum in', 'tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis', 'Good', 'Home and Garden', 'https://picsum.photos/id/494/320/320', 'in faucibus orci luctus et ultrices', 0, 0, 49.221751, -122.967222, 200, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (68, 'user7@shareandget.com', 'feugiat non pretium quis lectus suspendisse potenti in eleifend', 'in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna', 'New', 'Cars', 'https://picsum.photos/id/878/320/320', 'vestibulum sed magna at nunc', 0, 0, 49.170901, -122.935536, 109, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (69, 'user7@shareandget.com', 'in magna bibendum imperdiet nullam orci pede venenatis', 'commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing', 'Like new', 'Home and Garden', 'https://picsum.photos/id/750/320/320', 'augue vestibulum ante ipsum', 0, 0, 49.135326, -122.974012, 12, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (70, 'user7@shareandget.com', 'adipiscing lorem vitae mattis nibh ligula', 'ipsum aliquam non mauris morbi non lectus aliquam sit amet diam', 'Used', 'Home and Garden', 'https://picsum.photos/id/823/320/320', 'aenean lectus', 0, 0, 49.232309, -122.950876, 121, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (71, 'user8@shareandget.com', 'venenatis turpis enim blandit mi in porttitor pede justo', 'in magna bibendum imperdiet nullam orci pede venenatis non sodales', 'Used', 'Cars', 'https://picsum.photos/id/805/320/320', 'ante ipsum', 0, 0, 49.196146, -123.103988, 63, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (72, 'user8@shareandget.com', 'est et tempus semper est quam pharetra', 'interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis', 'Good', 'Electronics', 'https://picsum.photos/id/640/320/320', 'dolor sit amet consectetuer adipiscing elit proin interdum', 0, 0, 49.147534, -122.934861, 20, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (73, 'user8@shareandget.com', 'id lobortis convallis tortor risus dapibus augue', 'nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut', 'Like new', 'Others', 'https://picsum.photos/id/117/320/320', 'nunc rhoncus dui vel sem sed sagittis nam congue risus', 0, 0, 49.122112, -122.893371, 75, 0);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (74, 'user8@shareandget.com', 'cubilia curae mauris', 'pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices', 'Good', 'Others', 'https://picsum.photos/id/647/320/320', 'nulla sed', 0, 0, 49.214771, -123.095394, 18, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (75, 'user8@shareandget.com', 'volutpat sapien arcu sed augue aliquam', 'maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas', 'Used', 'Others', 'https://picsum.photos/id/112/320/320', 'tristique', 0, 0, 49.194071, -122.963584, 61, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (76, 'user8@shareandget.com', 'eget elit sodales scelerisque mauris sit amet', 'nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris', 'Used', 'Others', 'https://picsum.photos/id/612/320/320', 'sapien dignissim vestibulum vestibulum ante ipsum primis in', 0, 0, 49.10134, -122.913574, 23, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (77, 'user8@shareandget.com', 'praesent blandit lacinia erat vestibulum sed magna at', 'nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis', 'New', 'Cars', 'https://picsum.photos/id/196/320/320', 'sed justo', 0, 0, 49.165202, -123.119397, 117, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (78, 'user8@shareandget.com', 'lobortis sapien', 'faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam', 'Like new', 'Others', 'https://picsum.photos/id/207/320/320', 'neque aenean auctor gravida sem praesent', 0, 0, 49.203374, -123.025182, 197, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (79, 'user8@shareandget.com', 'magna vulputate luctus cum sociis natoque penatibus et', 'semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam', 'Used', 'Electronics', 'https://picsum.photos/id/499/320/320', 'vivamus in felis eu sapien cursus vestibulum proin eu mi', 0, 0, 49.13419, -122.940368, 102, 0);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (80, 'user8@shareandget.com', 'ornare consequat', 'maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam', 'Like new', 'Cars', 'https://picsum.photos/id/473/320/320', 'enim lorem ipsum', 0, 0, 49.113806, -123.163966, 58, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (81, 'user9@shareandget.com', 'massa quis augue luctus tincidunt nulla mollis', 'duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum', 'Used', 'Home and Garden', 'https://picsum.photos/id/501/320/320', 'accumsan odio curabitur convallis', 0, 0, 49.124572, -122.918472, 158, 0);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (82, 'user9@shareandget.com', 'ipsum integer a nibh in quis justo maecenas rhoncus aliquam', 'nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna', 'Used', 'Home and Garden', 'https://picsum.photos/id/120/320/320', 'lectus aliquam sit amet diam in', 0, 0, 49.093646, -123.1742, 28, 0);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (83, 'user9@shareandget.com', 'in faucibus orci luctus et ultrices posuere cubilia curae', 'magna at nunc commodo placerat praesent blandit nam nulla integer', 'Used', 'Home and Garden', 'https://picsum.photos/id/614/320/320', 'quisque ut erat curabitur gravida', 0, 0, 49.116627, -123.181431, 133, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (84, 'user9@shareandget.com', 'in lacus curabitur', 'donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies', 'Good', 'Electronics', 'https://picsum.photos/id/50/320/320', 'elit sodales scelerisque mauris sit amet eros suspendisse accumsan', 0, 0, 49.246036, -122.962192, 138, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (85, 'user9@shareandget.com', 'tortor id nulla', 'magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis', 'Used', 'Cars', 'https://picsum.photos/id/766/320/320', 'sapien non mi integer ac neque duis', 0, 0, 49.21943, -123.091025, 161, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (86, 'user9@shareandget.com', 'quis turpis sed ante vivamus tortor duis mattis egestas metus', 'vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare', 'New', 'Home and Garden', 'https://picsum.photos/id/306/320/320', 'ut mauris eget', 0, 0, 49.177817, -123.05305, 68, 0);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (87, 'user9@shareandget.com', 'mauris eget massa tempor convallis nulla neque libero convallis eget', 'leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque', 'Good', 'Others', 'https://picsum.photos/id/687/320/320', 'erat', 0, 0, 49.109704, -122.868886, 193, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (88, 'user9@shareandget.com', 'rhoncus aliquet', 'luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien', 'Like new', 'Home and Garden', 'https://picsum.photos/id/261/320/320', 'tincidunt nulla mollis molestie lorem quisque', 0, 0, 49.142816, -122.924774, 166, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (89, 'user9@shareandget.com', 'dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis', 'sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi', 'Good', 'Home and Garden', 'https://picsum.photos/id/690/320/320', 'sit amet lobortis sapien sapien non mi', 0, 0, 49.10475, -123.070039, 104, 0);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (90, 'user9@shareandget.com', 'magna bibendum imperdiet nullam orci pede venenatis non', 'vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis', 'Good', 'Others', 'https://picsum.photos/id/606/320/320', 'ut mauris eget massa tempor convallis nulla', 0, 0, 49.164473, -123.147222, 130, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (91, 'user10@shareandget.com', 'orci nullam molestie nibh in', 'eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere', 'Like new', 'Electronics', 'https://picsum.photos/id/399/320/320', 'vestibulum ante ipsum primis in faucibus orci', 0, 0, 49.182951, -122.818091, 107, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (92, 'user10@shareandget.com', 'vitae nisi nam ultrices libero non mattis pulvinar nulla', 'imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum', 'Used', 'Home and Garden', 'https://picsum.photos/id/177/320/320', 'dolor morbi vel lectus in quam fringilla rhoncus mauris enim', 0, 0, 49.091271, -122.891962, 128, 0);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (93, 'user10@shareandget.com', 'augue vel accumsan tellus nisi', 'tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse', 'Good', 'Cars', 'https://picsum.photos/id/273/320/320', 'odio elementum', 0, 0, 49.212059, -123.128416, 95, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (94, 'user10@shareandget.com', 'ipsum primis in faucibus', 'aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis', 'Like new', 'Electronics', 'https://picsum.photos/id/307/320/320', 'erat curabitur gravida nisi at nibh in hac habitasse platea', 0, 0, 49.245456, -122.799667, 74, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (95, 'user10@shareandget.com', 'amet nulla quisque arcu libero rutrum ac lobortis vel dapibus', 'ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus', 'Like new', 'Home and Garden', 'https://picsum.photos/id/307/320/320', 'tempus semper est quam pharetra magna ac consequat metus sapien', 0, 0, 49.165553, -122.912331, 145, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (96, 'user10@shareandget.com', 'augue vestibulum ante', 'lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut', 'Used', 'Home and Garden', 'https://picsum.photos/id/588/320/320', 'lacinia erat vestibulum sed magna at', 0, 0, 49.243779, -123.172602, 165, 0);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (97, 'user10@shareandget.com', 'posuere cubilia curae nulla dapibus dolor vel est donec', 'convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in', 'New', 'Others', 'https://picsum.photos/id/504/320/320', 'cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus', 0, 0, 49.15029, -122.820785, 105, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (98, 'user10@shareandget.com', 'iaculis diam erat fermentum justo nec condimentum', 'suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus', 'New', 'Home and Garden', 'https://picsum.photos/id/633/320/320', 'est lacinia nisi', 0, 0, 49.108226, -123.105106, 160, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (99, 'user10@shareandget.com', 'tempus sit amet sem fusce consequat nulla', 'proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut', 'Like new', 'Others', 'https://picsum.photos/id/383/320/320', 'cras in purus eu magna vulputate luctus cum', 0, 0, 49.111954, -123.018527, 122, 1);
insert into items (id, ownerId, name, description, `condition`, category, imageURLs, tags, numberOfReview, averageRating, lat, lng, price, isActive) values (100, 'user10@shareandget.com', 'quisque id justo', 'eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia', 'New', 'Home and Garden', 'https://picsum.photos/id/946/320/320', 'lectus pellentesque at nulla', 0, 0, 49.21161, -122.924682, 174, 1);